# Generated by Django 5.0.1 on 2024-01-25 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("credit_card_app", "0002_creditcardinfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CreditCardInfo",
        ),
    ]
